### ISSUE TITLE
How to turn off the channel correctly？

### ISSUE THREAD

**Issue by meguoe** [jwalton/node-amqp-connection-manager#132]
How to turn off the channel correctly, channel.close () does not seem to work, resulting in a large number of channels in rabbitmq

**Comment by jwalton** [comment]
`channel.close()` should close the channel.  Do you have channels sticking around or queues sticking around?  If you want a queue to clean itself up when the channel closes you can do something like:

```
channel.assertQueue(queueName, { exclusive: true, autoDelete: true });
```

This library is just a wrapper around [amqplib](http://www.squaremobius.net/amqp.node/channel_api.html#channel_close) though, so that might be a better place to get help, or since this isn't really an issue, maybe stackoverflow?
