### ISSUE TITLE
Providing SASL Config

### ISSUE THREAD

**Issue by Hussain1993** [jwalton/node-amqp-connection-manager#137]
Hi,

We are trying to connect to our RabbitMQ instance which is protected by TLS.  I get the following error when trying to connect:

`SASL mechanism PLAIN is not provided by the server`.

Speaking to another person within my team they needed to set their SASL mechanism to EXTERNAL - but they are using a Java client. 

Is there a way of changing the SASL mechanism that is used when creating the connection to the RabbitMQ instance? I have looked at the connectionOptions object and could not find anything there. 

Thanks

**Comment by jwalton** [comment]
I'm afraid I'm far from a RabbitMQ expert - this library is really a thin wrapper around https://www.npmjs.com/package/amqplib, and just makes sure that we reconnect if the server disconnects.  So I'd start by looking at that library and seeing if the options you need are there.  If there's something that needs to change in this library, I'm happy to accept a PR or even make the changes provided I understand what needs to be changed.  :)

**Comment by Hussain1993** [comment]
Just as a reference for people in the future who might come across the same issue. The way that you add SASL external credentials to this library is by doing the following:

`import {credentials} from "amqplib";
// other imports go here


const connection = amqp.connect(["url to rabbitmq"], {
   connectionOptions: {
       ca: [fs.readFileSync('path/to/ca')],
       cert: fs.readFileSync('path/to/cert'),
       key: fs.readFileSync('path/to/key'),
       rejectUnauthorised: false,
       //@ts-ignore
      credentials: credentials.external();
   }
})`

**Comment by GiltosMx** [comment]
Hey @jwalton, maybe you already know this but I believe this issue could already be resolved. If I'm understanding correctly, the remaining task here is that the `connectionOptions` doesn't have the correct type definitions for `credentials` when using the library with **Typescript**. This doesn't seem to require any code changes to the actual JavaScript code.

I checked and I'm pretty sure that @Hussain1993 might be using an older version of the [@types/amqp-connection-manager](https://www.npmjs.com/package/@types/amqp-connection-manager). Those types are coming from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/amqp-connection-manager), and I see specifically the `credentials` attribute was added fairly recently in [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/amqp-connection-manager/index.d.ts#L45) and with [this Pull Request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42426).

Updating the types definitions to versions `^2.0.6` should make it so that `@ts-ignore` directive is not needed anymore.

**Comment by jwalton** [comment]
One of these days I'll rewrite this library in TS natively. Whenever I have to do work on it, I always think, "What? This isn't in typescript?"  :P
