### ISSUE TITLE
setImmediate error

### ISSUE THREAD

**Issue by Mattchewone** [jwalton/node-amqp-connection-manager#140]
Hey,

I've been using this library on a project for a while and it's been great! So thanks!

Recently we started to see this error and I can't see what might be causing it:
```
/app/node_modules/amqp-connection-manager/lib/ChannelWrapper.js:337
setImmediate(() => resolve(result));
^
ReferenceError: Cannot access 'result' before initialization
```

Any help on how what might be causing this?

**Comment by jwalton** [comment]
What version of amqp-connection-manager do you have installed?  (`npm ls amqp-connection-manager` should tell you.)  And what version of node.js (`node -v`)?  Do you have a full stack trace, too?  `lib/ChannelWrapper.js:337` is in the middle of a comment, so that's probably not where things are going wrong.  :)
