### ISSUE TITLE
Option to send messages in bulk

### ISSUE THREAD

**Issue by tankorbox** [jwalton/node-amqp-connection-manager#65]
I see your idea in  **_messages** on **ChannelWrapper** is data preserving. But i realized that the performance is low (in my system only ~300msgs/s rate from producer to RabbitMQ) - One message can only be sent after previous message has callback return. Any option to send message in bulk asynchorous without waiting others. Or you can suggest me some properly way to do this. Thank you so much.

**Comment by jwalton** [comment]
You can send multiple messages without waiting for the callback to return.  For example:

```
for(const message of messages) {
    await channel.publish(...);
}
```

Will send each message sequentially, waiting for each to be finished, but:

```
for(const message of messages) {
    channel.publish(...).catch(err => console.log("Bad things happened. :(");
}
```

Will fire off all your messages at once, since we're not `await`ing each one.  You could also do something like:

```
await Promise.all(messages.map(message => channel.publish(...)));
```

Which will send a big block of messages all at once, wait for all of them to be successfully delivered, and error back if any one of them fails (although, you don't know which ones failed in this case).

**Comment by tankorbox** [comment]
Thank you so much for responses. I successfully apply new implement to send multiple messages. The app's performance improved perfectly. But I have a problem. when a large number of request call sendToQueue, node app reached max heap and die. Would you mind raising any solution for this case?
And I have one question about your code implementation. Why did you call publishQueueMessage recursive. It may be more heavier than using loop??

**Comment by jwalton** [comment]
`_publishQueuedMessages` isn't *really* recursive - it calls itself from inside the `Promise().then()`, which is always resolved after a call to `setImmediate()`, so it's not as if this is going to blow the stack or anything.  But, reaching max heap certainly sounds bad.  :P

**Comment by jwalton** [comment]
Fixed by https://github.com/benbria/node-amqp-connection-manager/pull/84.
