### ISSUE TITLE
removeSetup() triggers error

### ISSUE THREAD

**Issue by WebmasterClickPanda** [jwalton/node-amqp-connection-manager#92]
Hello!

I am unable to remove a setup, probably I have the wrong sintax, is there any way to get a working example of the removeSetup function?

This is the piece of code triggering the error
```
Channel.removeSetup(function(channel) {
return Promise.all([
channel.prefetch(1),
channel.consume(current_ip, processMsg)
])})
```

And this is the error returned:

TypeError: Cannot read property 'length' of null
at Object.pb.applyFn (/home/mailing_servicesV2/node_modules/promise-breaker/index.js:214:20)
at Object.pb.call (/home/mailing_servicesV2/node_modules/promise-breaker/index.js:293:23)
at /home/mailing_servicesV2/node_modules/amqp-connection-manager/lib/ChannelWrapper.js:74:104

Or else, how can I pause consuming messages on a channel without closing it?

**Comment by dixakman** [comment]
+++ need help)

**Comment by FrancisLiberty** [comment]
Old issue, but answering since it is still open here.

@WebmasterClickPanda. the removeSetup needs to be called with the reference to the setup function that was already added with addSetup.
eg what you could do is:
```
function doSetup(channel) {
return Promise.all([
channel.prefetch(1),
channel.consume(current_ip, processMsg)
])}
await yourChannel.addSetup(doSetup);
```
And then at some place in your code where you determine that this setup function is not needed anymore
```
yourChannel.removeSetup(doSetup);
```
